# [build.environment]
#   NPM_FLAGS = "--version" # prevent Netlify npm install
# [build]
#   command = 'npx pnpm i --store=node_modules/.pnpm-store && npm run build'
#   publish = 'dist'
# Forward requests to /legacy if the browser sends a cookie 
# named `is_legacy` or `my_other_cookie`
# [[redirects]]
# force = false
# from = "/*"
# to = "/writing/:splat"
# status = 301
# from = "/*"
# to = "/legacy/:splat"
# force = false
# conditions = {Cookie = ["is_legacy","my_other_cookie"]}
